language: python

env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34

install:
  - mkdir /tmp/elasticsearch
  - wget -O - https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.7.4.tar.gz | tar xz --directory=/tmp/elasticsearch --strip-components=1
  - pip install tox coveralls

before_script:
  - /tmp/elasticsearch/bin/elasticsearch -d -D es.path.data=/tmp -D es.discovery.zen.ping.multicast.enabled=false -Des.node.bench=true
  - sleep 5

script:
  - tox

after_success:
  - coveralls
